# Values in <> should be changed with exact values

version: '3'
services:
  api:
    image: microblink/api:1.23.0
    # To avoid security issues run application as non-root user `microblink`
    # before application run create user on the host machine and enable write permissions for
    # all mounted volumes
    # user: microblink

    # All available environment variables are documented in Dockerfile
    # https://github.com/microblink/docker/blob/master/api/Dockerfile
    environment:
      - LICENSEE=<FROM_https://microblink.com/customer/licences>
      - LICENSE_KEY=<FROM_https://microblink.com/customer/licences>
      - PORT=${PORT-8080}

      # Basic authentication is enabled when username and password are defined
      - BASIC_AUTH_USERNAME=microblink
      # Password should be an BCrypt hash
      # characters '$' should be escaped as '$$'
      # Example: plain password 'microblink123' as BCrypt hash
      - BASIC_AUTH_PASSWORD=$$2y$$12$$i4/BHvnVt.RemfBDF2GCqed.bN3LKN9.zkODvvmlA8h1Xg5vyhBdC

      # Limit image upload size to {x}MB, by default limiting is disabled (unlimited file size is allowed)
      # Example: limit to 10.25MB
      - MICROBLINK_IMAGE_SIZE_LIMIT_IN_MB=10.25

      # This is Optional if you want to use Microblink API via NGINX proxy
      # and to use Let's Encrypt as SSL certificate provider
      - VIRTUAL_HOST=<api.microblink.YOUR_DOMAIN.com>
      # It should be 8080 because Java SPring application inside of Docker image is hosted on port 8080 inside of container
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=<api.microblink.YOUR_DOMAIN.com>
      - LETSENCRYPT_EMAIL=<EMAIL_ADDRESS where Let's Encrypt will send notifications>

      # NOTE: only the last one Docker env variable with the same name will be used.
      # Do not set JAVA_OPTS more than once, the last one will override previous defined.
      # Multiple options define in the one JAVA_OPTS value.

      # Customize internal Java Spring application for specific use-case.
      # EXAMPLES
      - JAVA_OPTS=-Xmx6g -Dserver.ssl.enabled=true
      # - JAVA_OPTS=-Dserver.ssl.enabled=true -Dserver.ssl.key-store-type=PKCS12 -Dserver.ssl.key-store=/custom/mounted/path/my-custom-keystore.p12 -Dserver.ssl.key-store-password=my-custom-keytore-password -Dserver.ssl.key-alias=custom-key-alias

      # Set maximum size for JVM memory allocation pool.
      # Recommended to set 1GB less than available RAM memory on the machine,
      # if container has not defined any memory limit.
      # If container has set usage memory limit then this value should be 256MB less than available
      # container's memory limit.
      - JAVA_OPTS=-Xmx8g

      # Experimental JDK feature for automatic memory allocation defined by Linux cgroup
      # NOTE: Deprecated option '-XX:+UseCGroupMemoryLimitForHeap' in OpenJDK 10 and removed in the OpenJDK 11!
      # Please use only in DEV environment for performance testing purposes with MAX JDK 9
      # - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -XshowSettings:vm

      # HTTPS with Java max heap 3GB
      # - JAVA_OPTS=-Xmx3g -Dserver.ssl.enabled=true

    restart: unless-stopped
    volumes:
      - ./logs:/opt/microblink-api-ws/logs
    ports:
      - "80:${PORT-8080}"

networks:
  default:
    external:
      name: microblink
